### ISSUE TITLE
[Client] Post View , Design

### ISSUE THREAD

**Issue by Jeong-HW** [codestates/Dawn-on-client#44]
### **TODO**

- [ ]  상세 보기 페이지 완성하기
- [ ]  게시물 작성 테스트 및 수정 기능 완성하기
- [ ]  마무리 디자인 작업
