### ISSUE TITLE
[Client] Viewer , Landing Page

### ISSUE THREAD

**Issue by Jeong-HW** [codestates/Dawn-on-client#52]
### **TODO**

- [x]  페이지 오른쪽 상세보기 뷰어 구현
- [x]  MyFeed: PATCH 요청
- [x]  전체적인 디자인 보완
