### ISSUE TITLE
[Client] Initial Visual Studio Setting , 로그인, 회원가입, 로그아웃 구조 설계

### ISSUE THREAD

**Issue by Jeong-HW** [codestates/Dawn-on-client#6]
### **TODO**

- [x]  Vs code 기본 세팅 / 컴포넌트 및 페이지 설계
- [x] 개인피드 구조 수정
- [x]  Nav.js 조건 분기
- [x]  로그인 , 회원가입 Modal
