### ISSUE TITLE
[Client] Refactoring : Responsive Web View

### ISSUE THREAD

**Issue by Jeong-HW** [codestates/Dawn-on-client#62]
### **TODO**

- [x]  랜딩페이지 반응형 : "section 3" 이미지 교체 및 전체 레이아웃 수정 , footer 수정
- [x]  커스텀 플래너 반응형 : 업로드 버튼 추가 , 해시태그 버그 수정
- [x]  네비게이션 바 반응형 : 양옆 여백 줄이기 , My feed 버튼 비활성화
- [x]  로그인 & 회원가입 모달창 반응형 : 중앙 배치
- [x]  모아보기 페이지 : 세로 배치 (가로 스크롤) , 왼쪽 사이드바 👉  "display: none"
